### ISSUE TITLE
Novice

### ISSUE THREAD

**Issue by baquialla** [timtester123/M3U_VOD_Downloader#1]
Sorry ..I'm a novice...The dialog box asks me  to use a "m3u8 plus format" I've have just a m3u address and ID Pass.How can I do to format from a normal M3U8 Playlist?.Thx

**Comment by timtester123** [comment]
Hi,
please use the following format:

http://your.url.address:NUMBER/get.php?username=YOURNAME&password=PASSWORD&type=m3u_plus&output=mpegts
